config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :portfolios
  resources :users
  resources :groups
  resources :mutual_funds

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'sign-up' => 'users#register', as: :register
  post 'sign-up' => 'users#create_register'

  get 'profile' => 'static_pages#profile'
  get 'legal' => 'static_pages#legal'
  get 'privacy' => 'static_pages#privacy'
  get 'help' => 'static_pages#help'

  get 'reviews' => 'reviews#index'

  resources :advisors
  resources :organizations do
    member do
      get 'add_advisors'
      patch 'add_advisors_create'
      get 'approve_advisors/:advisors_id' => 'organizations#approve_advisors', as: 'approve_advisors'
      get 'remove_advisors/:advisors_id' => 'organizations#remove_advisors', as: 'remove_advisors'

    end
  end

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  include ActiveModel::Validations

  belongs_to :user
  has_many :investments
  accepts_nested_attributes_for :investments, allow_destroy: true, reject_if: proc { |attributes| attributes['ticker'].blank? }
  attr_accessor :pie_data
  attr_accessor :alerts
  validates_presence_of :management_fee


  def market_value
    if @market_value
      return @market_value
    end
    total_value = 0
    investments = Investment.where(portfolio_id: self.id)
    investments.each do |investment|
      total_value = total_value + investment.market_value
    end
    @market_value = total_value
  end

  def average_expense_ratio
    if @average_expense_ratio
      return @average_expense_ratio
    end
    average_expense_ratio = 0
    investments = Investment.where(portfolio_id: self.id)
    investments.each do |investment|
      percent = investment.market_value / self.market_value
      portion = percent * investment.expense_ratio
      average_expense_ratio = average_expense_ratio + portion
    end
    @average_expense_ratio = average_expense_ratio
  end

  def average_12b1_fee
    if @average_12b1_fee
      return @average_12b1_fee
    end
    average_12b1_fee = 0
    self.investments.each do |investment|
      percent = investment.market_value / self.market_value
      portion = percent * investment.twelve_b_1
      average_12b1_fee = average_12b1_fee + portion
    end
    @average_12b1_fee = average_12b1_fee
  end

  def average_load_fee
    if @average_load_fee
      return @average_load_fee
    end
    average_load_fee = 0
    self.investments.each do |investment|
      percent = investment.market_value / self.market_value
      portion = percent * investment.load
      average_load_fee = average_load_fee + portion
    end
    @average_load_fee = average_load_fee
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :destroy, :update]
  include BrokersHelper


  def new
    @portfolio = Portfolio.new
    @portfolio.investments.build
  end

  def edit
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    @portfolio.user_id = session[:user_id]
    if @portfolio.save
      redirect_to portfolios_path, notice: 'Portfolio was saved.'
    else
      render 'portfolios/new'
    end
  end

  def index
    if auth_group('Managers')
      @portfolios = Portfolio.all
    else
      @portfolios = Portfolio.where(:user_id => session[:user_id])
    end
  end

  def show
    unless @portfolio.user_id == session[:user_id] || auth_group('Administrators')
      redirect_to portfolios_path, notice: 'Access to this portfolio is denied.'
    end
    @investments = Investment.where(:portfolio => @portfolio.id)

    #todo: round values

    pie_data = [ ['Broker Fees', @portfolio.management_fee],
                 ['Expense Fees', @portfolio.average_expense_ratio],
                 ['Load Fees', @portfolio.average_load_fee],
                 ['12B-1 Fees', @portfolio.average_12b1_fee]
    ]
    @portfolio.pie_data = pie_data
    @brokerage = brokerage_ad
  end


  def update
    nickname = @portfolio.nickname
    if @portfolio.update_attributes(portfolio_params)
      redirect_to portfolios_path, notice: "The portfolio \"#{nickname}\" was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    deleted_portfolio = @portfolio.nickname
    @portfolio.destroy
    redirect_to portfolios_url, notice: "#{deleted_portfolio} was successfully deleted."
  end

private
  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:nickname, :management_fee, investments_attributes: [:id, :ticker, :quantity, :_destroy])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def add_investment(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render('investments/table_form', f: builder)
    end
    link_to(name, '#', class: 'btn btn-primary add_field', data: {id: id, fields: fields.gsub("\n", '')})
  end
end

app/views/portfolios/edit.html.erb
<% provide(:title, 'Edit Portfolio') %>
<h1>Edit Portfolio</h1>
<%= form_for @portfolio do |f| %>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-4 col-sm-5 col-xs-8">
        <%= label_tag('User', 'User') %><br>
        Ability to reassign portfolios, coming soon<br>
        <%= label_tag('Nickname', 'Nickname') %>
        <%= f.text_field :nickname, placeholder: '', class: 'form-control' %> <br>
        <%= label_tag('ManagementFee', 'Management Fee') %>
        <%= f.text_field :management_fee, size: 20, placeholder: 'XX.XX%', class: 'form-control' %> <br>
      </div>
      <div class="clearfix"></div>
      <div class="col-md-8 col-sm-8 col-xs-8">
        <h3>Investments</h3>
        <table style="margin-bottom: 6px">
          <thead>
          <tr>
            <td>Ticker Symbol</td>
            <td>Shares</td>
            <td>Remove Investment</td>
            <td><%= f.text_field :id, class: 'hidden' %></td>
          </tr>
          </thead>
          <%= f.fields_for :investments do |builder| %>
              <%= render 'investments/table_form', f: builder  %>
          <% end %>
        </table>
        <%= add_investment 'Add Investment', f, :investments %>
      </div>
      <div class="clearfix"></div>
      <br>
      <%= f.submit class: 'btn btn-default'  %>
    </div>
<% end %>

app/views/portfolios/index.html.erb
<% provide(:title, 'View Portfolios') %>
<%= render partial: 'shared/notice' %>
<h1>Portfolio List</h1>
<%= link_to_button 'Create Portfolio', new_portfolio_path, 'btn-primary' %>
<table class='table'>
  <thead>
  <tr>
    <th>Name</th>
    <%= auth_group('Managers') ? '<th>User</th>'.html_safe : '' %>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.nickname %></td>
        <%= auth_group('Managers') ? '<td>'.html_safe + (link_to portfolio.user.full_name, user_path(portfolio.user)) + '</td>'.html_safe : '' %>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Delete', portfolio, method: :delete, data: {confirm: 'Are you sure?'}  %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br/>

app/views/portfolios/new.html.erb
<% provide(:title, 'Input Data') %>
<h1>Create Portfolio</h1>
<%= render partial: 'shared/errors', :locals => {:object => @portfolio}%>
<%= form_for @portfolio do |f| %>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-3 col-sm-5 col-xs-8">
        <%= label_tag('Nickname', 'Nickname') %>
        <%= f.text_field :nickname, placeholder: '', class: 'form-control' %> <br>
        <%= label_tag('ManagementFee', 'Management Fee') %>
        <%= f.text_field :management_fee, placeholder: 'XX.XX%', class: 'form-control' %> <br>
      </div>
      <div class="clearfix"></div>
      <div class="col-md-8 col-sm-8 col-xs-8">
        <h3>Investments</h3>
        <table style="margin-bottom: 6px">
          <thead>
          <tr>
            <td>Ticker Symbol</td>
            <td>Shares</td>
            <td>Remove Investment</td>
          </tr>
          </thead>
          <%= f.fields_for :investments do |builder| %>
                <%= render 'investments/table_form', f: builder  %>
          <% end %>
        </table>
        <%= add_investment 'Add Investment', f, :investments %>
      </div>
      <div class="clearfix"></div>
      <br>
      <%= f.submit class: 'btn btn-default'  %>
    </div>
<% end %>

app/views/portfolios/show.html.erb
<div class="row">

<div class="col-xs-12 col-lg-6" style="margin-top: 40px;  background-color: #ffffff; border: solid; border-color: #dddddd">
  <h2 style="text-align: center">Fee Breakdown</h2>
  <%= pie_chart @portfolio.pie_data %>
</div>
<div class="col-xs-12 col-lg-4" style="margin-top: 40px">
  <table class="table table-bordered breakdown-table">
    <tr>
      <th colspan="3" style="text-align: center;">Fees to Advisor</th>
    </tr>
    <tr>
      <td>Current Management Fee</td>
      <td><%= number_with_precision(@portfolio.management_fee, precision: 2) %>%</td>
      <td>$<%= number_with_precision((@portfolio.management_fee * @portfolio.market_value) / 100, precision: 2) %></td>
    </tr>
    <tr>
      <th colspan="3" style="text-align: center;">Fees to Fund</th>
    </tr>
    <tr>
      <td>Average Expense Ratio</td>
      <td><%= number_with_precision(@portfolio.average_expense_ratio, precision: 2) %>%</td>
      <td>$<%= number_with_precision((@portfolio.average_expense_ratio * @portfolio.market_value) / 100, precision: 2) %></td>
    </tr>
    <tr>
      <th colspan="3" style="text-align: center;">Kickback to Advisor</th>
    </tr>
    <tr>
      <td>Average 12B-1 Fee</td>
      <td><%= number_with_precision(@portfolio.average_12b1_fee, precision: 2) %>%</td>
      <td>$<%= number_with_precision((@portfolio.average_12b1_fee * @portfolio.market_value) / 100, precision: 2) %></td>
    </tr>
    <tr>
      <td>Average Load Fee</td>
      <td><%= number_with_precision(@portfolio.average_load_fee, precision: 2) %>%</td>
      <td>$<%= number_with_precision((@portfolio.average_load_fee * @portfolio.market_value) / 100, precision: 2) %></td>
    </tr>
    <tr>
      <th colspan="3" style="text-align: center;">Total Fees</th>
    </tr>
    <tr>
      <td>Total Fees Per Year</td>
      <td><%= number_with_precision((@portfolio.average_expense_ratio + @portfolio.management_fee), precision: 2 )%>%</td>
      <td>$<%= number_with_precision(((@portfolio.average_expense_ratio + @portfolio.management_fee) * @portfolio.market_value) / 100, precision: 2 )%></td>
    </tr>
    <tr>
      <td>Total Fees Per Sale</td>
      <td><%= number_with_precision((@portfolio.average_12b1_fee + @portfolio.average_load_fee), precision: 2 )%>%</td>
      <td>$<%= number_with_precision(((@portfolio.average_12b1_fee + @portfolio.average_load_fee) * @portfolio.market_value) / 100, precision: 2 )%></td>
    </tr>
    <tr>
      <td>Total Fees</td>
      <td colspan="2" style="text-align: center; color: red;">$<%= number_with_precision(((@portfolio.average_expense_ratio + @portfolio.management_fee + @portfolio.average_12b1_fee + @portfolio.average_load_fee) * @portfolio.market_value) / 100, precision: 2 )%></td>
    </tr>
  </table>

</div>

<div class="col-xs-12 col-lg-2" style="margin-top: 40px"><h2>Ad Coming Soon</h2></div>
</div>
<div class="row">
<div class="col-lg-12" >
  <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Symbol</th>
          <th>Shares</th>
          <th>Current Price</th>
          <th>Load Fees <i class="fa fa-question-circle" id="load-fees-info" data-toggle="tooltip" data-placement="top" title="Load Fees Info"></i></th>
          <th>12B-1 Fees <i class="fa fa-question-circle" id="twelve-b-1-info" data-toggle="popover" data-placement="top" title="12-B-1 Info" data-content="Log story of stuff. Log story of stuff. Log story of stuff. Log story of stuff. "></i></th>
          <th>Expense Ratio <i class="fa fa-question-circle" id="expense-ratio-info" data-toggle="tooltip" data-placement="top" title="Expense Ratio Info"></i></th>
          <th>Market Value</th>
        </tr>
      </thead>
      <tbody>
          <% @investments.each do |i| %>
            <tr>
              <td><%= i.ticker.upcase %></td>
              <td><%= i.quantity %></td>
              <td>$<%= number_with_precision(i.nav, precision: 2) %></td>
              <td><%= number_with_precision(i.load, precision: 2) %>%</td>
              <td><%= number_with_precision(i.twelve_b_1, precision: 2) %>%</td>
              <td><%= number_with_precision(i.expense_ratio, precision: 2) %>%</td>
              <td>$<%= number_with_precision(i.nav * i.quantity, precision: 2) %></td>
            </tr>
          <% end %>
      <tr>
        <th colspan="6">Portfolio Value</th>
        <th>$<%= number_with_precision(@portfolio.market_value, precision: 2) %></th>
      </tr>
      </tbody>
    </table>
</div>
</div>