config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :portfolios
  resources :users
  resources :groups
  resources :mutual_funds

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'sign-up' => 'users#register', as: :register
  post 'sign-up' => 'users#create_register'

  get 'profile' => 'static_pages#profile'
  get 'legal' => 'static_pages#legal'
  get 'privacy' => 'static_pages#privacy'
  get 'help' => 'static_pages#help'

  get 'reviews' => 'reviews#index'

  resources :advisors
  resources :organizations do
    member do
      get 'add_advisors'
      patch 'add_advisors_create'
      get 'approve_advisors/:advisors_id' => 'organizations#approve_advisors', as: 'approve_advisors'
      get 'remove_advisors/:advisors_id' => 'organizations#remove_advisors', as: 'remove_advisors'

    end
  end

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  has_many :organization_advisors
  has_many :organizations, through: :organization_advisors



  has_many :users, through: :user_advisors
  accepts_nested_attributes_for :users
  has_many :advisor_admins

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :address1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def image_
    if @image
      return @image
    end
    if self.image
      @image = self.image
    end
  end


  def formatted_phone
    "(#{phone[0...3]}) #{phone[3...6]}-#{phone[6...10]}"
  end

end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  before_action :set_advisor, only: [:show, :destroy, :edit, :update]

  before_action do
    auth_groups_redirect(['Administrators', 'Managers'])
  end

  def index
    @advisors = Advisor.all
  end

  def new
    @advisor = Advisor.new
    @advisor.is_verified = true
  end

  def create
    @advisor = Advisor.new(advisor_params)
    if @advisor.save
      advisor_admin = AdvisorAdmin.new
      advisor_admin.advisor_id = @advisor.id
      advisor_admin.user_id = session[:user_id]
      advisor_admin.is_verified = true
      advisor_admin.save
      organization_advisor = OrganizationAdvisor.new
      organization_advisor.advisor_id = @advisor.id
      organization_advisor.organization_id = params[:organization][:organization_id]
      organization_advisor.is_verified = true
      organization_advisor.save
      redirect_to advisors_path, notice: 'Investment Advisor was created.'
    else
      render 'advisors/new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @advisor.update_attributes(advisor_params)
      #! input email user fu
      redirect_to advisors_path, notice: "The user \"#{@advisor.full_name}\" was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    deleted_advisor = @advisor.full_name
    if @advisor.destroy
      redirect_to advisors_path, notice: "#{deleted_advisor} was successfully deleted."
    end
  end

  private
  def set_advisor
    @advisor = Advisor.find(params[:id])
  end

  def advisor_params
    params.require(:advisor).permit(:first_name, :last_name, :image, :phone, :email, :address1, :address2, :city, :state, :zip, :is_verified)
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_form.html.erb
<%= render partial: 'shared/errors', :locals => {:object => @advisor}%>
<div class="col-md-4 col-lg-4">
  <%= form_for @advisor, :html => { :multipart => true} do |f| %>
      <% if params[:action] == 'new' %>
          <div class="form-group col-lg-12">
            <%= f.check_box :is_verified %> <%= f.label :is_verified %>
          </div>
      <% end %>
      <%= render 'advisors/sub_form', f: f %>
      <div class="clearfix" style="margin-bottom: 10px"></div>
      <div class="form-group">
        <%= f.submit 'Save Investment Advisor', class: 'btn btn-success' %>
      </div>
  <% end %>
</div>

app/views/advisors/_sub_form.erb
<div class="form-group col-lg-10">
  <span style="font-weight: bold">Advisor Information</span>
  <%= f.label :first_name, class: 'sr-only' %>
  <%= f.text_field :first_name, class: 'form-control top-input', placeholder: 'First Name' %>
  <%= f.label :last_name, class: 'sr-only' %>
  <%= f.text_field :last_name, class: 'form-control bottom-input', placeholder: 'Last Name'%>
</div>
<div class="form-group col-lg-10">
  <%= f.label :phone, class: 'sr-only'  %>
  <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone Number' %>
</div>
<div class="form-group col-lg-12">
  <%= f.label :email, class: 'sr-only'  %>
  <%= f.text_field :email, class: 'form-control', placeholder: 'Email Address' %>
</div>
<div class="form-group col-lg-12">
  <% if params[:action_name] == 'edit' %>
      <%= image_tag @advisor.image_url.to_s, width: 150 %> <br>
  <% end %>
  <%= f.label :image, 'Upload Image', class: 'btn btn-primary trigger'  %>
  <%= f.file_field :image, style: 'display:none;', class: 'uploadBtn' %>
</div>
<div class="form-group col-lg-12">
  <span style="font-weight: bold">Advisor Address</span>
  <%= f.label :address1, class: 'sr-only' %>
  <%= f.text_field :address1, class: 'form-control top-input', placeholder: 'Address' %>
  <%= f.label :address2, class: 'sr-only' %>
  <%= f.text_field :address2, class: 'form-control bottom-input', placeholder: 'Address 2'%>
</div>
<div class="form-group col-lg-10">
  <%= f.label :city, class: 'sr-only' %>
  <%= f.text_field :city, class: 'form-control', placeholder: 'City' %>
</div>
<div class="form-group col-lg-12">
  <div class="col-lg-6">
    <%= f.label :state, class: 'sr-only' %>
    <%= f.select :state, options_for_select(us_states), {}, class: 'form-control' %>
  </div>
  <div class="col-lg-6">
    <%= f.label :zip, class: 'sr-only' %>
    <%= f.text_field :zip, class: 'form-control', placeholder: 'Zip' %>
  </div>
</div>
<div class="form-group col-lg-12">
    <%= f.label :organization, 'Associate with Organization' %>
    <%= collection_select :organization, :organization_id,  Organization.order(:name), :id, :name, {:prompt => true}, {:class=>'form-control'}%>
</div>

app/views/advisors/edit.html.erb
<% provide(:title, 'Edit Investment Advisor') %>
<h2>Edit Investment Advisor</h2>
<%= render partial: 'advisors/form' %>

app/views/advisors/index.html.erb
<%= render partial: 'shared/notice' %>
<h1>Investment Advisors</h1>
<%= link_to_button 'Create Investment Advisor', new_advisor_path, 'btn-primary' %>
<table class='table'>
  <thead>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th colspan="4">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @advisors.each do |advisor| %>
      <tr>
        <td><%= advisor.full_name %></td>
        <td><%= advisor.formatted_phone %></td>
        <td><%= link_to 'Show', advisor %></td>
        <% if advisor.is_verified %>
            <td></td>
        <% else %>
            <td></td>
        <% end %>
        <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
        <td><%= link_to 'Delete', advisor, method: :delete, data: {confirm: 'Are you sure?'}  %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br/>

app/views/advisors/new.html.erb
<% provide(:title, 'Create Investment Advisor') %>
<h2>Create Investment Advisor</h2>
<%= render partial: 'advisors/form' %>

app/views/advisors/show.html.erb
<h1><%= @advisor.full_name %></h1>
Advisor ID: <%= @advisor.id %><br>
Phone: <%= @advisor.formatted_phone %><br>
Email: <%= @advisor.email %><br>
Address: <%= @advisor.address1 %> <br>
<% if @advisor.address2 %>
    <%= @advisor.address2 %> <br>
<% end %>
<%= @advisor.city %>, <%= @advisor.state %> <%= @advisor.zip %> <br>

<% @advisor.organizations.each do |organization| %>
    <h4>Organization: <%= organization.name %></h4>
    Name: <%= organization.name %> <br>
    Phone: <%= organization.formatted_phone %> <br>
    Email: <%= organization.email %> <br>
    Address: <%= organization.address1 %> <br>
    <% if organization.address2 %>
        <%= organization.address2 %> <br>
    <% end %>
    <%= organization.city %>, <%= organization.state %> <%= organization.zip %> <br>
<% end %>