config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :portfolios
  resources :users
  resources :groups
  resources :mutual_funds

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'sign-up' => 'users#register', as: :register
  post 'sign-up' => 'users#create_register'

  get 'profile' => 'static_pages#profile'
  get 'legal' => 'static_pages#legal'
  get 'privacy' => 'static_pages#privacy'
  get 'help' => 'static_pages#help'

  get 'reviews' => 'reviews#index'

  resources :advisors
  resources :organizations do
    member do
      get 'add_advisors'
      patch 'add_advisors_create'
      get 'approve_advisors/:advisors_id' => 'organizations#approve_advisors', as: 'approve_advisors'
      get 'remove_advisors/:advisors_id' => 'organizations#remove_advisors', as: 'remove_advisors'

    end
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :organization_admins
  has_many :users, through: :organization_admins

  has_many :organization_advisors
  has_many :advisors, through: :organization_advisors
  accepts_nested_attributes_for :organization_advisors, allow_destroy: true

  def formatted_phone
    "(#{phone[0...3]}) #{phone[3...6]}-#{phone[6...10]}"
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :destroy, :edit, :update, :add_advisors, :add_advisors_create]
  before_action :auth, except: [:show]

  def new
    @organization = Organization.new
    @organization.is_verified = true
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      user_advisor = OrganizationAdmin.new
      user_advisor.organization_id = @organization.id
      user_advisor.user_id = session[:user_id]
      user_advisor.is_verified = true
      user_advisor.save
      redirect_to organizations_path, notice: 'Organization was created.'
    else
      render 'organizations/new'
    end
  end

  def add_advisors
    @organization.organization_advisors.build
    @organization.organization_advisors.each do |oa|
      oa.is_verified = true
    end
  end

  def add_advisors_create
    if @organization.update_attributes(organization_params)
      redirect_to organizations_path, notice: 'Advisor was added.'
    else
      render :add_advisors
    end
  end

  def approve_advisors
    organization_advisor = OrganizationAdvisor.where(:organization_id=>params[:id]).where(:advisor_id=>params[:advisors_id]).first
    organization_advisor.is_verified = true
    organization_advisor.save
    redirect_to organization_path(params[:id])
  end

  def remove_advisors
    organization_advisor = OrganizationAdvisor.where(:organization_id=>params[:id]).where(:advisor_id=>params[:advisors_id]).first
    organization_advisor.is_verified = false
    organization_advisor.save
    redirect_to organization_path(params[:id])
  end

  def edit
  end

  def update
    if @organization.update_attributes(organization_params)
      redirect_to organizations_path, notice: 'Organization was saved.'
    else
      render 'organizations/new'
    end
  end

  def show
  end

  def index
    @organizations = Organization.all
  end

  def destroy
    deleted_organization = @organization.name
    if @organization.destroy
      redirect_to organizations_path, notice: "#{deleted_organization} was successfully deleted."
    end
  end

  private
  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:id, :name, :image, :phone, :email, :address1, :address2, :city, :state, :zip, :is_verified, organization_advisors_attributes: [:id, :advisor_id, :is_verified, :_destroy])
  end

  def advisors_params
    params.require(:organization).permit(advisors_params[:id])
  end

  def auth
    auth_groups_redirect(['Administrators', 'Managers'])
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def add_advisor(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render('organizations/add_advisors_form', f: builder)
    end
    link_to(name, '#', class: 'btn btn-primary add_field', data: {id: id, fields: fields.gsub("\n", '')})
  end
end

app/views/organizations/_add_advisors_form.html.erb
<tr>
  <td><%= f.text_field :advisor_id, class: 'form-control' %></td>
  <td><%= f.check_box :is_verified %></td>
  <td><span style="padding-top:-20px;"><%= f.hidden_field :_destroy %><%= link_to 'remove', '#', class: 'remove_fields btn btn-danger' %></span></td>
</tr>

app/views/organizations/_form.html.erb
<%= render partial: 'shared/errors', :locals => {:object => @organization}%>
<div class="col-md-4 col-lg-4">
  <%= form_for @organization, :html => { :multipart => true} do |f| %>
      <% if params[:action] == 'new' %>
          <div class="form-group col-lg-12">
            <%= f.check_box :is_verified %> <%= f.label :is_verified %>
          </div>
      <% end %>
      <%= render 'organizations/form_items', f: f %>
      <div class="clearfix" style="margin-bottom: 10px"></div>
      <div class="form-group">
        <%= f.submit 'Save Investment Organization', class: 'btn btn-success' %>
      </div>
  <% end %>
</div>

app/views/organizations/_form_items.erb
<div class="form-group col-lg-10">
  <%= f.label :name, class: 'sr-only' %>
  <%= f.text_field :name, class: 'form-control top-input', placeholder: 'Name' %>
</div>
<div class="form-group col-lg-10">
  <%= f.label :phone, class: 'sr-only'  %>
  <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone Number' %>
</div>
<div class="form-group col-lg-12">
  <%= f.label :email, class: 'sr-only'  %>
  <%= f.text_field :email, class: 'form-control', placeholder: 'Email Address' %>
</div>
<div class="form-group col-lg-12">
  <% if params[:action_name] == 'edit' %>
      <%= image_tag @advisor.image_url.to_s, width: 150 %> <br>
  <% end %>
  <%= f.label :image, 'Upload Image', class: 'btn btn-primary trigger'  %>
  <%= f.file_field :image, style: 'display:none;', class: 'uploadBtn' %>
</div>
<div class="form-group col-lg-12">
  <%= f.label :address1, class: 'sr-only' %>
  <%= f.text_field :address1, class: 'form-control top-input', placeholder: 'Address' %>
  <%= f.label :address2, class: 'sr-only' %>
  <%= f.text_field :address2, class: 'form-control bottom-input', placeholder: 'Address 2'%>
</div>
<div class="form-group col-lg-10">
  <%= f.label :city, class: 'sr-only' %>
  <%= f.text_field :city, class: 'form-control', placeholder: 'City' %>
</div>
<div class="form-group col-lg-12">
  <div class="col-lg-6">
    <%= f.label :state, class: 'sr-only' %>
    <%= f.select :state, options_for_select(us_states), {}, class: 'form-control' %>
  </div>
  <div class="col-lg-6">
    <%= f.label :zip, class: 'sr-only' %>
    <%= f.text_field :zip, class: 'form-control', placeholder: 'Zip' %>
  </div>
</div>

app/views/organizations/add_advisors.erb
<%= render partial: 'shared/errors', :locals => {:object => @organization}%>
<div class="col-md-4 col-lg-4">
  <%= form_for @organization, :url => { :action => :add_advisors_create } do |f| %>
          <table class="table">
            <tr>
              <th>Advisor ID</th>
              <th>Verified</th>
              <th></th>
            </tr>
            <%= f.fields_for :organization_advisors do |builder| %>
                <%= render('organizations/add_advisors_form', f: builder) %>
            <% end %>
          </table>
          <%= add_advisor 'Add Advisor', f, :organization_advisors %>
      <div class="form-group">
        <%= f.submit 'Save Investment Organization', class: 'btn btn-success' %>
      </div>
  <% end %>
</div>

app/views/organizations/edit.html.erb
<% provide(:title, 'Edit Investment Organization') %>
<h2>Edit Investment Organzation</h2>
<%= render partial: 'organizations/form' %>

app/views/organizations/index.html.erb
<%= render partial: 'shared/notice' %>
<h1>Investment Organizations</h1>
<%= link_to_button 'Create Investment Organization', new_organization_path, 'btn-primary' %>
<table class='table'>
  <thead>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th colspan="5">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.formatted_phone %></td>
        <td><%= link_to 'Show', organization %></td>
        <% if organization.is_verified %>
            <td></td>
        <% else %>
            <td></td>
        <% end %>
        <td><%= link_to 'Add Advisors', add_advisors_organization_path(organization) %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Delete', organization, method: :delete, data: {confirm: 'Are you sure?'}  %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br/>

app/views/organizations/new.html.erb
<% provide(:title, 'Create Investment Organization') %>
<h2>Create Investment Organzation</h2>
<%= render partial: 'organizations/form' %>

app/views/organizations/show.html.erb
<h1>Organization: <%= @organization.name %></h1>
Name: <%= @organization.name %> <br>
Phone: <%= @organization.formatted_phone %> <br>
Email: <%= @organization.email %> <br>
Address: <%= @organization.address1 %> <br>
<% if @organization.address2 %>
    <%= @organization.address2 %> <br>
<% end %>
<%= @organization.city %>, <%= @organization.state %> <%= @organization.zip %> <br>
<hr>
<% if @organization.organization_advisors.where(is_verified: false).any? %>
    <h4>You have outstanding advisor request(s)</h4>
    <% @organization.advisors.each do |advisor| %>
        <% unless advisor.organization_advisors.first.is_verified %>
            <%= link_to 'Approve ' + advisor.full_name, approve_advisors_organization_path(@organization.id, advisor.id) %>
        <% end %>
    <% end %>
<% end %>
<h2>Advisors</h2>
<% @organization.advisors.each do |advisor| %>
    <% if advisor.organization_advisors.first.is_verified %>
        <h4><%= advisor.full_name %></h4>
        Advisor ID: <%= advisor.id %><br>
        Phone: <%= advisor.formatted_phone %><br>
        Email: <%= advisor.email %><br>
        Address: <%= advisor.address1 %> <br>
        <% if advisor.address2 %>
            <%= advisor.address2 %> <br>
        <% end %>
        <%= advisor.city %>, <%= advisor.state %> <%= advisor.zip %> <br>
        <%= link_to 'Remove ' + advisor.full_name, remove_advisors_organization_path(@organization.id, advisor.id) %>
    <% end %>
<% end %>